export const ADAPTER_IDS = {
  TEMPERATURE: "DHM:TEMPERATURE",
  HUMIDITY: "DHM:HUMIDITY",
  RAINFALL: "DHM:RAINFALL",
  WATER_LEVEL: "DHM:WATER_LEVEL",
  GLOFAS: "GLOFAS"
}

export const ADAPTER_ID_FILTERS: Record<string, string[]> = {
  HEAT_WAVE: [ADAPTER_IDS.TEMPERATURE, ADAPTER_IDS.HUMIDITY],
  FLOOD: [ADAPTER_IDS.RAINFALL, ADAPTER_IDS.WATER_LEVEL, ADAPTER_IDS.GLOFAS],
};