# Install dependencies only when needed
FROM node:18-alpine3.17 AS deps
WORKDIR /usr/src/app
COPY dist/apps/community-tool-ui/package.json .npmrc ./
RUN yarn install --production

FROM node:18-alpine3.17 AS runner
USER node
WORKDIR /usr/src/app
COPY --chown=node:node dist/apps/community-tool-ui ./
COPY --chown=node:node --from=deps /usr/src/app/node_modules ./node_modules
CMD [ "yarn", "start" ]