import { SampleTemplate } from 'apps/rahat-ui/src/common/download.beneficiary.sample.dialog';

// Add or remove entries here to change what shows up in the "Download Sample" dropdown.
export const BENEFICIARY_SAMPLE_TEMPLATES: SampleTemplate[] = [
  {
    value: 'mcn',
    label: 'MCN Beneficiary Sample',
    fileName: 'mcn_beneficiary_sample.xlsx',
    headers: [
      'Name*',
      'Phone Number',
      'Gender',
      'Age',
      'Government ID',
      'Location',
    ],
  },
  {
    value: 'nrcs-flood-cva',
    label: 'NRCS Flood CVA Sample',
    fileName: 'nrcs_flood_cva_beneficiary_sample.xlsx',
    headers: [
      'Name*',
      'Phone Number',
      'Gender',
      'Age',
      'Government ID Type',
      'Government ID',
      'Location',
      'District',
      'Municipality',
      'Ward Number',
      'Tole',
      'Household Head Name',
      'Household Head Gender',
      'Relationship with Household Head',
      'Number of Family Members',
      'House Condition',
      'Bank ac name',
      'Bank ac number',
      'Bank Name',
    ],
  },
  {
    value: 'nrcs-flood-banked-beneficiary',
    label: 'NRCS Flood Banked Beneficiary',
    fileName: 'nrcs_flood_banked_beneficiary_sample.xlsx',
    headers: [
      'Name*',
      'Phone Number',
      'Gender',
      'Age',
      'Government ID Type',
      'Government ID',
      'Location',
      'District',
      'Municipality',
      'Ward Number',
      'Tole',
      'Household Head Name',
      'Household Head Gender',
      'Relationship with Household Head',
      'Number of Family Members',
      'House Condition',
      'Bank ac name',
      'Bank ac number',
      'Bank Name',
    ],
  },
  {
    value: 'nrcs-flood-un-banked-beneficiary',
    label: 'NRCS Flood Un-banked Beneficiary',
    fileName: 'nrcs_flood_un-banked_beneficiary_sample.xlsx',
    headers: [
      'Name*',
      'Phone Number',
      'Gender',
      'Age',
      'Government ID Type',
      'Government ID',
      'Location',
      'District',
      'Municipality',
      'Ward Number',
      'Tole',
      'Household Head Name',
      'Household Head Gender',
      'Relationship with Household Head',
      'Number of Family Members',
      'House Condition',
    ],
  },
];
