export const PaginationTableName = {
  VENDOR_LIST: 'VENDOR_LIST',
  VENDOR_ONLINE_BENEFICIARY_LIST: 'VENDOR_ONLINE_BENEFICIARY_LIST',
  VENDOR_OFFLINE_BENEFICIARY_LIST: 'VENDOR_OFFLINE_BENEFICIARY_LIST',
};
