export const fieldLabels: Record<string, string> = {
  forecast: 'Forecast type',
  today: 'Today',
  tomorrow: 'Tomorrow',
  dayAfterTomorrow: 'Day after tomorrow',
  todayAfternoon: 'Today Afternoon',
  todayNight: 'Today Night',
  tomorrowAfternoon: 'Tomorrow Afternoon',
  tomorrowNight: 'Tomorrow Night',
  dayAfterTomorrowAfternoon: 'Day After Tomorrow Afternoon',
  dayAfterTomorrowNight: 'Day After Tomorrow Night',
  waterLevel: 'Water Level',
  hours24NWP: '24 Hours (NWP)',
  hours48: '48 Hours (NWP)',
  hours72NWP: '72 Hours (NWP)',
  heavyRainfallForecastInKarnaliBasin:
    'Heavy Rainfall Forecast in Karnali Basin',
  hours24: '24 Hours',
  hours72: '72 Hours',
  hours168: '168 Hours',
  extremeWeatherOutlook: 'Extreme Weather Outlook',
  deterministicsPredictionSystem: 'Deterministic Prediction System',
  probabilisticPredictionSystem: 'Probabilistic Prediction System',
  todayGLOFAS: 'Today (GLOFAS)',
  days3: '3 Days Forecast (GLOFAS)',
  days5: '5 Days Forecast (GLOFAS)',
  inBetweenTodayUntil7DaysIsThereAnyPossibilityOfPeak:
    'Peak Possibility in Next 7 Days',
  status: 'Status',
  gaugeReading: 'Gauge Reading',
  station: 'Station Name',
};
