// Values are translation keys in the 'AA Project' namespace, resolved by the
// caller's `t()` so validation messages render in the active locale.
export const fieldLabels: Record<string, string> = {
  forecast: 'FORECAST_TYPE',
  today: 'TODAY',
  tomorrow: 'TOMORROW',
  dayAfterTomorrow: 'DAY_AFTER_TOMORROW',
  todayAfternoon: 'TODAY_AFTERNOON',
  todayNight: 'TODAY_NIGHT',
  tomorrowAfternoon: 'TOMORROW_AFTERNOON',
  tomorrowNight: 'TOMORROW_NIGHT',
  dayAfterTomorrowAfternoon: 'DAY_AFTER_TOMORROW_AFTERNOON',
  dayAfterTomorrowNight: 'DAY_AFTER_TOMORROW_NIGHT',
  waterLevel: 'WATER_LEVEL',
  hours24NWP: 'N24_HOURS_NWP',
  hours48: 'N48_HOURS_NWP',
  hours72NWP: 'N72_HOURS_NWP',
  heavyRainfallForecastInKarnaliBasin: 'HEAVY_RAINFALL_FORECAST_KARNALI_BASIN',
  hours24: 'N24_HOURS',
  hours72: 'N72_HOURS',
  hours168: 'N168_HOURS',
  extremeWeatherOutlook: 'EXTREME_WEATHER_OUTLOOK',
  deterministicsPredictionSystem: 'DETERMINISTIC_PREDICTION_SYSTEM',
  probabilisticPredictionSystem: 'PROBABILISTIC_PREDICTION_SYSTEM',
  todayGLOFAS: 'TODAY_GLOFAS',
  days3: 'N3_DAYS_FORECAST_GLOFAS',
  days5: 'N5_DAYS_FORECAST_GLOFAS',
  inBetweenTodayUntil7DaysIsThereAnyPossibilityOfPeak: 'PEAK_POSSIBILITY_IN_NEXT_7_DAYS',
  status: 'STATUS',
  gaugeReading: 'GAUGE_READING',
  station: 'STATION_NAME',
  gaugeForecast: 'GAUGE_FORECAST',
};
