export const IMPORT_SOURCE = {
  KOBOTOOL: 'KOBOTOOL',
  EXCEL: 'EXCEL',
};

export const TARGET_FIELD = {
  FULL_NAME: 'fullName',
  FIRSTNAME: 'firstName',
  LASTNAME: 'lastName',
  LOCATION: 'location',
  PHONE: 'phone',
  EMAIL: 'email',
  GENDER: 'gender',
  BIRTH_DATE: 'birthDate',
  NOTES: 'notes',
  LATITUDE: 'latitude',
  LONGITUDE: 'longitude',
  PHONE_STATUS: 'phoneStatus',
  BANKED_STATUS: 'bankedStatus',
  INTERNET_STATUS: 'internetStatus',
};

export const BENEF_DB_FIELDS = [
  TARGET_FIELD.FULL_NAME,
  TARGET_FIELD.FIRSTNAME,
  TARGET_FIELD.LASTNAME,
  TARGET_FIELD.LOCATION,
  TARGET_FIELD.PHONE,
  TARGET_FIELD.EMAIL,
  TARGET_FIELD.GENDER,
  TARGET_FIELD.BIRTH_DATE,
  TARGET_FIELD.NOTES,
  TARGET_FIELD.LATITUDE,
  TARGET_FIELD.LONGITUDE,
  TARGET_FIELD.PHONE_STATUS,
  TARGET_FIELD.BANKED_STATUS,
  TARGET_FIELD.INTERNET_STATUS,
];
