export const TAGS = {
  GET_BENEFICIARY: 'get_one_beneficiary',
  GET_ALL_USER: 'get_all_user',
  GET_USER: 'get_user',
  UPDATE_USER: 'update_user',
  CREATE_USER: 'create_user',
  GET_ALL_PROJECTS: 'get_all_projects',
  GET_ALL_ROLES: 'get_all_roles',
  GET_ROLE: 'get_role',
  CREATE_ROLE: 'create_role',
  EDIT_ROLE: 'edit_role',
  DELETE_ROLE: 'delete_role',
  GET_ALL_CAMPAIGNS: 'get_all_campaign',
  GET_CAMPAIGNS: 'get_campaign',
  GET_CAMPAIGNS_AUDIO: 'get_campaign_audio',
  GET_ALL_TRANSPORT: 'get_all_transport',
  GET_ALL_AUDIENCE: 'get_all_audience',
  GET_BENEFICIARIES: 'get_beneficiaries',
  GET_BENEFICIARIES_STATUS: 'get_beneficiaries_status',
  LIST_COMMUNITY_BENFICIARIES: 'list_community_beneficiaries',
  CREATE_COMMUNITY_BENEFICARY: 'create_community_beneficary',
  UPDATE_COMMUNITY_BENEFICARY: 'update_community_beneficary',
  REMOVE_COMMUNITY_BENEFICARY: 'remove_community_beneficary',
  CREATE_BULK_COMMUNITY_BENEFICARY: 'create_bulk_community_beneficary',
  CREATE_COMMUNITY_SETTINGS: 'create_community_settings',
  LIST_COMMUNITY_SETTINGS: 'list_community_settings',
  GET_VENDORS: 'list_vendors',
  GET_VENDOR_DETAILS: 'get_vendors_details',
  GET_PROJECT_DETAILS: 'get_project_details',
  LIST_COMMUNITY_GROUP: 'list_community_group',
  LIST_COMMUNITY_GROUP_BY_ID: 'list_community_group_by_id',
  ADD_COMMUNITY_GROUP: 'add_community_group',
  ADD_COMMUNITY_BENEFICIARY_GROUP: 'add_community_beneficiary_group',
  LIST_COMMUNITY_BENEFICIARY_GROUP: 'list_community_beneficiary_group',
  LIST_ACTIVE_FIELD_DEFINITIONS: 'list_active_field_definitions',
  LIST_COMMUNITY_FIELD_DEFINITIONS: 'list_community_field_definitions',
  CREATE_COMMUNITY_FIELD_DEFINITIONS: 'create_community_field_definitions',
  UPDATE_COMMUNITY_FIELD_DEFINITIONS: 'update_community_field_definitions',
  UPDATE_COMMUNITY_FIELD_DEFINITIONS_STATUS:
    'update_community_field_definitions_status',
  DOWNLOAD_COMMUNITY_GROUPED_BENEFICIARIES:
    'download_community_grouped_beneficiaries',
  GET_COMMUNITY_BENEFICARY_STATS: 'get_community_beneficiary_stats',
  LIST_TARGETING: 'list_targeting',
  ADD_BULK_FIELD_DEFINITIONS: 'add_bulk_field_definitions',
  CREATE_TARGETING: 'create_targeting',
  REMOVE_COMMUNITY_GROUP: 'remove_community_group',
  PURGE_COMMUNITY_GROUP: 'purge_community_group',
  GET_TARGETING_BENEFICIARIES: 'get_targeting_beneficiary',
  LIST_KOBO_SETTINGS: 'list_kobo_settings',
  LIST_MAPPINGS_BY_IMPORT_ID: 'list_mappings_by_import_id',
  UPDATE_TARGETING_LABEL: 'update_targeting_label',
  DOWNLOAD_TARGETING_LABEL: 'download_targeting_label',
};
