name: Dev Aidlink CICD
on:
  push:
    branches:
      - 'init-aidlink-ui'
  pull_request:
    branches:
      - 'init-aidlink-ui'
  workflow_dispatch:

env:
  CI: false

jobs:
  rahat-ui:
    name: rahat-ui
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'action') || contains(github.event.pull_request.title, 'action') || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4

      - name: Get short SHA and short Run ID
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "run_id_short=${GITHUB_RUN_ID:0:3}" >> $GITHUB_OUTPUT

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            github/data/general/docker/esatya username | DOCKERHUB_USERNAME ;
            github/data/general/docker/esatya password | DOCKERHUB_TOKEN ;
            github/data/rahat/rahat-ui/dev/unicef/aidlink rahat-ui | ENV ;

      - name: create environment file
        run: |
          tee ./.env <<<"$ENV"

      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Install pnpm
        run: |
          npm install -g pnpm@8.14.1

      - name: Install dependencies
        run: pnpm install

      - name: install dependencies and build apps
        run: |
          pnpm build:all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # Rahat-UI Image
      - name: build && push rahat-ui
        id: build-push-rahat-ui
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.rahat-ui
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: |
            esatya/rahat-ui:dev-aidlink
            esatya/rahat-ui:dev-aidlink-${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.run_id_short }}

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      run_id_short: ${{ steps.vars.outputs.run_id_short }}