name: Stage CT CI/CD
on:
  push:
    branches:
      - 'stage'
  pull_request:
    branches:
      - 'stage'
  workflow_dispatch:

env:
  CI: false
  MANIFEST_FILE: 'K8s-Manifest/Rahat/CT-Stage/Argo-Rollout/ui.yaml'

jobs:
  community-tool-ui:
    name: community-tool-ui
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'action') || contains(github.event.pull_request.title, 'action') || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4

      - name: Get short SHA and short Run ID
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "run_id_short=${GITHUB_RUN_ID:0:3}" >> $GITHUB_OUTPUT

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            github/data/general/docker/estya username | DOCKERHUB_USERNAME ;
            github/data/general/docker/estya password | DOCKERHUB_TOKEN ;
            github/data/rahat/rahat-ui/stage/ct ct-ui | ENV ;

      - name: create environment file
        run: |
          tee ./.env <<<"$ENV"
          tee ./.npmrc <<<"$NPMRC"
      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
    
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8.14.1
          run_install: false

      - name: Install dependencies
        run: pnpm install     

      - name: install dependencies and build apps
        run: |
          pnpm build:all
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # Community-Tool-UI Image
      - name: build && push community-tool-ui
        id: build-push-community-tool-ui
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.community-tool-ui
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: |
            esatya/community-tool-ui:stage
            esatya/community-tool-ui:stage-${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.run_id_short }}

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      run_id_short: ${{ steps.vars.outputs.run_id_short }}

  update-manifest:
    name: Update Kubernetes Manifest
    needs: community-tool-ui
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            github/data/general/Stage-Manifest repo | MANIFEST_REPO ;
            github/data/general/Stage-Manifest ssh-key | SSH_KEY ;

      # Checkout the manifest repository using SSH
      - name: Checkout Stage Manifest Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFEST_REPO }}
          ssh-key: ${{ env.SSH_KEY }}

      # Update the image tag in the manifest
      - name: Update Image Tag in Manifest
        run: |
          sed -i "s|image: esatya/community-tool-ui:.*|image: esatya/community-tool-ui:stage-${{ needs.community-tool-ui.outputs.sha_short }}-${{ needs.community-tool-ui.outputs.run_id_short }}|" ${{ env.MANIFEST_FILE }}

      # Commit and push changes using SSH
      - name: Commit and Push Changes
        run: |
          git config user.name "sandab-rumsan"
          git config user.email "sandab@rumsan.net"
          git add ${{ env.MANIFEST_FILE }}
          git commit -m "runner: Update CT Stage Image tag to stage-${{ needs.community-tool-ui.outputs.sha_short }}-${{ needs.community-tool-ui.outputs.run_id_short }}"
          git push origin main