name: AA Test Load

on:
  push:
    branches:
      - test-load
  workflow_dispatch:

jobs:
  call-core:
    uses: rahataid/rahat-ui/.github/workflows/AA-Core-CICD.yaml@test-load
    with:
      apps_to_build: rahat-ui,community-tool-ui
      vault_path: testload
      tag_suffix: test-load
    secrets: inherit
